# App Info
ios_app_id                                : 1441472614                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Lose weight & live healthier, without a diet.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Christian, Lennart & Sebastian @ elbstack.com                              
your_link                                 : https://elbstack.com                     
your_city                                 : Hamburg                                
email_address                             : hello@chew.fit
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Fasting Tracker
    description                           : Chew is a simple fasting tracker used for Intermittent Fasting with the 16/8 method.
    fontawesome_icon_name                 : weight
    
  - title                                 : Intermittent Fasting
    description                           : Restrict your daily eating period to 8 hours. Then you fast for 16 hours in between.
    fontawesome_icon_name                 : utensils

  - title                                 : Motivation
    description                           : Document your Intermittent Fasting daily & stay motivated.
    fontawesome_icon_name                 : calendar-alt

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#25B8B8"
topbar_transparency                       : 0.1
topbar_title_color                        : "#006666"

cover_image                               : # assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ECFCFB"
cover_overlay_transparency                : 1.0

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#FF5500"

app_title_color                           : "#006666"
app_price_color                           : "#006666"
app_description_color                     : "#006666"

feature_title_color                       : "#151413"
feature_text_color                        : "#2F2E2B"

feature_icons_foreground_color            : "#FF6933"
feature_icons_background_color            : "#FFD9CC"

social_icons_foreground_color             : "#FF6933"
social_icons_background_color             : "#FFD9CC"

footer_text_color                         : "#2F2E2B"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
